### ISSUE TITLE
Download instructions need some love

### ISSUE THREAD

**Issue by tseemann** [phe-bioinformatics/pms#1]
The instructions are not sufficient to get MOST running:

https://github.com/phe-bioinformatics/MOST#instruction-on-how-to-download-mlst-database

I assume you mean the pubMLST files for `senterica` scheme?

It seems you already bundle them in `MLST_data` ?

I assume they are the same as mine I bundle:
https://github.com/tseemann/mlst/tree/master/db/pubmlst/senterica

**Comment by RTewolde** [comment]
Thanks for your comment Torsten. I have amended the README document to make running MOST clearer.  

I assume you mean the pubMLST files for senterica scheme?
Download  senterica scheme  from pubMLST and then change the file format by following the instruction in the in README document. Examples are given in the MLST_data  directory. 

I assume they are the same as mine I bundle:
They are similar to your data set but you need to
i.   Change the file name (senterica.txt to profiles.txt file)  and remove the clonal_complex column 
ii.   Rename the *.tfa files to *.fas file
iii.  If you want to inferring Salmonella  serotype  include the   mlst_lookup.txt file ( MLST_data/salmonella / mlst_lookup.txt) . mlst_lookup.txt  is PHE Salmonella serotype database.
