### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by Wang-Jing-NZ** [phe-bioinformatics/pms#2]
Just tried to run MOST and got the following error msg:

> There was an error in the function 'score'
> ---
> 
> Traceback (most recent call last):
>   File "/media/disk2/MOST/modules/utility_functions.py", line 243, in try_and_except
>     return function(_parameters, *_named_parameters)
>   File "/media/disk2/MOST/modules/MLST_read_pileup_file.py", line 145, in score
>     v, indel, array_of_all_indels,most_common_indel = pile(t[2], t[4])
> ## IndexError: list index out of range

Look like a familiar python loop error. Any help and suggestion please, Cheers

**Comment by RTewolde** [comment]
Which samtools version are you using? MOST script will only work using  samtools 0.1.18.

**Comment by Wang-Jing-NZ** [comment]
thanks - it works now. I let MOST point to the right version of samtools,
