### ISSUE TITLE
some explaination on  --workflow

### ISSUE THREAD

**Issue by Wang-Jing-NZ** [phe-bioinformatics/pms#3]
How to apply the -w parameter? Can you give an example? 
Cheers

**Comment by RTewolde** [comment]
ST can be determined by specifying a workflow and full path to the input directory (fastq directory). The input directory should contain only a pair of fastq files.

For example: 
1. To determine ST from salmonella, run the script by using the following pathway

 python MOST.py -w salmonella  -i < full path to the input directory> e.g /home/Wang-Jing-NZ/salmonella_fastq_file
1. To determine ST from escherichia-coli , run the script by using the following pathway
   python MOST.py -w escherichia-coli -i < full path to the input directory> e.g /home/Wang-Jing-NZ/escherichia-coli_fastq_file

Within the MLST_data directory  ( MOST/MLST_data), there are a set of databases.  If you want to use the –w parameter, first check if the database exist in the  MLST_data directory.

**Comment by Wang-Jing-NZ** [comment]
thank you for the examples. --workflow is to select the right mlst schema to be used here. Also good to know that only a pair of fastq files in the input directory.

Cheers
Jing
